### ISSUE TITLE
Commands do not fail gracefully

### ISSUE THREAD

**Issue by sirhcm** [datares/discord-bot#3]
All commands should be updated with a surrounding try/catch statement or more complex error handling to avoid crashing nodejs and also to provide the end user with a more helpful error message.

**Comment by colinpcurtis** [comment]
Should be fixed by last set of commits

```js
	else if (commandName === 'whoami') {
		const res = await whoami(user_id);
		if (!res) {
			await interaction.reply('Your account is not verified, please verify your account using /iam and /verify first');
			return;
		}
		await interaction.reply(`Email: ${res.email}\nTeam: ${res.team}`);
	}
```

**Comment by colinpcurtis** [comment]
feel free to pull and test, and close issue if satisfied.

For other commands, we should probably wrap the command handling in `index.js` with try/catch blocks to return a graceful message even if we get some sort of code error.

**Comment by sirhcm** [comment]
Yeah, that definitely fixes the `/whoami` error, but for the other commands, we still need that try/catch, so I'll update this issue to reflect that.

**Comment by colinpcurtis** [comment]
yeah I think try/catch is ugly though, so I think we just need solid error handling in all downstream functions and a lot of good testing to make sure everything works as expected.

**Comment by colinpcurtis** [comment]
This will probably take some time, so it might be a weekend issue
